//
//  AppleTokenInfo.swift
//  
//
//  Created by Nikolai Nobadi on 5/28/23.
//

/// `AppleTokenInfo` is a typealias for a tuple containing information related to an Apple ID token.
/// This structure is tailored for use with Firebase Authentication.
///
/// The `tokenIdString` is a string representation of the ID token that is generated by Apple during the sign-in process and is used for Firebase authentication.
/// The `nonce` is a string that helps prevent replay attacks and is also generated during the sign-in process.
public typealias AppleTokenInfo = (tokenIdString: String, nonce: String)
